openapi: 3.0.1
info:
  title: Party Service
  version: 1.0.0
  description: CRUD Microservice for Party data
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://localhost:8080
    description: Dev server

paths:
  /api/v1/parties/{id}:
    get:
      tags: [Party]
      summary: Get a party by ID
      operationId: getPartyById
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier for the party
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved party
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartyResponse'
        '404':
          description: Party not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

    patch:
      tags: [Party]
      summary: Update a party by ID
      operationId: updateParty
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier for the party
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartyUpdate'
      responses:
        '200':
          description: Successfully updated party
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartyResponse'
        '400':
          description: Bad request (e.g. malformed JSON)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '404':
          description: Party not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '422':
          description: Unprocessable entity (e.g. failed validation)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableError'

  /api/v1/parties:
    post:
      tags: [Party]
      summary: Create a new party
      operationId: createParty
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartyCreate'
      responses:
        '201':
          description: Successfully created party
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartyResponse'
        '400':
          description: Bad request (malformed JSON)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '422':
          description: Unprocessable entity (validation failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableError'

components:
  schemas:
    # --- Create Schemas ---
    PartyCreate:
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          example: "John"
          description: "First name (letters, spaces, hyphens, periods, and apostrophes only)"
        middleName:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          example: "A."
          description: "Middle name or initial (letters, spaces, hyphens, periods, and apostrophes only)"
        lastName:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          example: "Doe"
          description: "Last name (letters, spaces, hyphens, periods, and apostrophes only)"
        email:
          type: string
          format: email
          minLength: 3
          maxLength: 254
          pattern: '^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$'
          example: "john.doe@example.com"
          description: "Valid email address"
        phoneNumber:
          type: string
          pattern: '^\d{3}-\d{3}-\d{4}$'
          example: "555-123-4567"
          description: "US phone number in format xxx-xxx-xxxx"
        address:
          $ref: '#/components/schemas/AddressCreate'
        meta:
          $ref: '#/components/schemas/MetaCreate'
      required:
        - firstName
        - lastName
        - address
        - email
        - phoneNumber
        - meta
      description: >
        All fields are required except for middleName.
        At least one of `email` or `phoneNumber` must be provided.

    AddressCreate:
      type: object
      properties:
        streetOne:
          type: string
          minLength: 1
          maxLength: 200
          example: "123 Main St"
          description: "Primary street address"
        streetTwo:
          type: string
          minLength: 1
          maxLength: 200
          example: "Apt 4B"
          description: "Secondary address line (apartment, suite, etc.)"
        city:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          example: "Springfield"
          description: "City name (letters, spaces, hyphens, periods, and apostrophes only)"
        state:
          type: string
          minLength: 2
          maxLength: 2
          pattern: '^[A-Za-z]{2}$'
          example: "IL"
          description: "US state code (two letters, case insensitive)"
        zip:
          type: string
          minLength: 3
          maxLength: 10
          pattern: '^[a-zA-Z0-9\s\-]+$'
          example: "62704"
          description: "Postal/ZIP code (alphanumeric, spaces, and hyphens allowed)"
        countryCode:
          type: string
          minLength: 2
          maxLength: 2
          pattern: '^[A-Z]{2}$'
          example: "US"
          description: "ISO 3166-1 alpha-2 country code (uppercase)"
        meta:
          $ref: '#/components/schemas/MetaCreate'
      required:
        - streetOne
        - city
        - state
        - zip
        - countryCode
        - meta

    MetaCreate:
      type: object
      properties:
        createdBy:
          type: string
          minLength: 1
          example: "user@example.com"
          description: "Identifier of the user creating the resource"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
          description: "Timestamp when the resource is created"
      required:
        - createdBy
        - createdAt

    # --- Update Schemas ---
    PartyUpdate:
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          description: "First name (letters, spaces, hyphens, periods, and apostrophes only)"
        middleName:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          description: "Middle name or initial (letters, spaces, hyphens, periods, and apostrophes only)"
        lastName:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          description: "Last name (letters, spaces, hyphens, periods, and apostrophes only)"
        email:
          type: string
          format: email
          minLength: 3
          maxLength: 254
          pattern: '^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$'
          description: "Valid email address"
        phoneNumber:
          type: string
          pattern: '^\d{3}-\d{3}-\d{4}$'
          example: "555-123-4567"
          description: "US phone number in format xxx-xxx-xxxx"
        address:
          $ref: '#/components/schemas/AddressUpdate'
        meta:
          $ref: '#/components/schemas/MetaUpdate'
      description: "All fields are optional for updates. Only provided fields will be updated."

    AddressUpdate:
      type: object
      properties:
        streetOne:
          type: string
          minLength: 1
          maxLength: 200
          example: "123 Main St"
          description: "Primary street address"
        streetTwo:
          type: string
          minLength: 1
          maxLength: 200
          example: "Apt 4B"
          description: "Secondary address line (apartment, suite, etc.)"
        city:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z\s\-\.'']+$'
          example: "Springfield"
          description: "City name (letters, spaces, hyphens, periods, and apostrophes only)"
        state:
          type: string
          minLength: 2
          maxLength: 2
          pattern: '^[A-Za-z]{2}$'
          example: "IL"
          description: "US state code (two letters, case insensitive)"
        zip:
          type: string
          minLength: 3
          maxLength: 10
          pattern: '^[a-zA-Z0-9\s\-]+$'
          example: "62704"
          description: "Postal/ZIP code (alphanumeric, spaces, and hyphens allowed)"
        countryCode:
          type: string
          minLength: 2
          maxLength: 2
          pattern: '^[A-Z]{2}$'
          example: "US"
          description: "ISO 3166-1 alpha-2 country code (uppercase)"
        meta:
          $ref: '#/components/schemas/MetaUpdate'
      description: "All fields are optional. Only provided fields will be updated."

    MetaUpdate:
      type: object
      properties:
        updatedBy:
          type: string
          minLength: 1
          example: "user@example.com"
          description: "Identifier of the user updating the resource"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T15:45:00Z"
          description: "Timestamp when the resource is updated"
      required:
        - updatedBy
        - updatedAt

    # --- Response Schemas ---
    PartyResponse:
      type: object
      properties:
        id:
          type: integer
          example: 123
        firstName:
          type: string
          example: "John"
        middleName:
          type: string
          example: "A."
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        phoneNumber:
          type: string
          example: "555-123-4567"
        address:
          $ref: '#/components/schemas/AddressResponse'
        meta:
          $ref: '#/components/schemas/MetaResponse'
      required:
        - id
        - firstName
        - lastName
        - email
        - phoneNumber
        - address
        - meta

    AddressResponse:
      type: object
      properties:
        id:
          type: integer
          example: 456
        streetOne:
          type: string
          example: "123 Main St"
        streetTwo:
          type: string
          example: "Apt 4B"
        city:
          type: string
          example: "Springfield"
        state:
          type: string
          example: "IL"
        zip:
          type: string
          example: "62704"
        countryCode:
          type: string
          example: "US"
        meta:
          $ref: '#/components/schemas/MetaResponse'
      required:
        - id
        - streetOne
        - city
        - state
        - zip
        - countryCode
        - meta

    MetaResponse:
      type: object
      properties:
        createdBy:
          type: string
          example: "user@example.com"
        updatedBy:
          type: string
          example: "admin@example.com"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T15:45:00Z"
      required:
        - createdBy
        - createdAt

    # --- Error Schemas ---
    ErrorBase:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - timestamp
        - status
        - error
        - message
        - path

    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/ErrorBase'
      description: The request cannot be processed because it is malformed.

    UnprocessableError:
      allOf:
        - $ref: '#/components/schemas/ErrorBase'
      description: The request is well-formed but contains invalid data.

    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/ErrorBase'
      description: The requested resource could not be found.
