"""drop party hash column.

Revision ID: dae1dfa3fda3
Revises: ff5d363e23af
Create Date: 2025-11-16 20:33:40.005222

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dae1dfa3fda3"
down_revision: Union[str, Sequence[str], None] = "ff5d363e23af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(schema="party_service", table_name="party", column_name="hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("party_history", schema="party_service")
    op.drop_table("party", schema="party_service")
    op.drop_table("address", schema="party_service")
    # ### end Alembic commands ###
