"""rename zip column to postal code.

Revision ID: ff5d363e23af
Revises: a490856f700b
Create Date: 2025-11-09 12:49:29.706699

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff5d363e23af"
down_revision: Union[str, Sequence[str], None] = "a490856f700b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        schema="party_service",
        table_name="address",
        column_name="zip_code",
        new_column_name="postal_code",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
